language: python
python:
	- "3.5"
branches:
  only:
    - master
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - git submodule update --init --recursive
script: ./script/deploy.sh
