name: deploy blog workflow
on:
  push:
    branches:
      - main

jobs:
  build_job:
    name: deploy blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: run deploy.sh
        run: script/deploy.sh
        shell: bash
      # ビルドの実行結果を Slack に投稿する
      - name: Send notification to slack channel
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "Job Result: ${{ job.status }}"
          SLACK_TITLE: Job Result
          SLACK_USERNAME: rtamp
