name: deploy blog workflow
on:
  push:
    branches:
      - main

jobs:
  build_job:
    name: deploy blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodule: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: run deploy.sh
        run: script/deploy.sh
        shell: bash
